name       : pdfarranger
version    : 1.7.0
release    : 5
source     :
    - https://github.com/pdfarranger/pdfarranger/archive/1.7.0.tar.gz : 00b03ebb07726deb2bbf6589482ef40616de8bc4d097c519fb213a9fd0fa79ea
homepage   : https://github.com/jeromerobert/pdfarranger
license    : GPL-3.0-or-later
component  : office
summary    : Small application to merge or split pdf documents and rotate, crop and rearrange their pages using an interactive and intuitive graphical interface
description: |
    pdfarranger is a small python-gtk application, which helps the user to merge or split pdf documents and rotate, crop and rearrange their pages using an interactive and intuitive graphical interface. It is a frontend for pikepdf.
builddeps  :
    - python-distutils-extra
rundeps    :
    - img2pdf
    - poppler
    - python-gobject
    - python-pikepdf
    - python3-cairo
build      : |
    %python3_setup
install    : |
    %python3_install
