name       : pdfarranger
version    : 1.8.0
release    : 10
source     :
    - https://github.com/pdfarranger/pdfarranger/archive/1.8.0.tar.gz : 7e2b0fb311c35e8d241cd498aacf42d718b54785b0a0ac059335bd5222640b82
homepage   : https://github.com/jeromerobert/pdfarranger
license    : GPL-3.0-or-later
component  : office
summary    : A simple application for merging, rearranging, splitting and modifing PDF files
description: |
    pdfarranger is a small python-gtk application, which helps the user to merge or split pdf documents and rotate, crop and rearrange their pages using an interactive and intuitive graphical interface. It is a frontend for pikepdf.
builddeps  :
    - python-distutils-extra
rundeps    :
    - img2pdf
    - poppler
    - python-dateutil
    - python-gobject
    - python3-cairo
build      : |
    %python3_setup
install    : |
    %python3_install
